# .github/workflows/update-countdown.yml

name: Update Release Countdown

on:
  schedule:
    - cron: '0 * * * *'       # every hour; adjust to daily ('0 0 * * *') if you prefer
  workflow_dispatch:         # allows manual runs

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout using your PAT stored in secrets.secret_ak
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.secret_ak }}

      # 2. Set up Node.js (needed for the countdown script)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 3. Run your countdown-generation script (no extra deps needed)
      - name: Generate countdown
        run: node scripts/updateCountdown.js

      # 4. Configure Git to use PAT for pushes
      - name: Configure Git to use PAT
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.secret_ak }}@github.com/${{ github.repository }}.git

      # 5. Commit & Push changes if readme.md was updated
      - name: Commit & Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add readme.md
          git commit -m "chore: update release countdown"
          git push
